# Generated by Django 5.0.1 on 2024-01-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
    ]
