# Generated by Django 5.0.1 on 2024-01-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_electronicalparts_electronicequipment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='electronicalParts',
        ),
        migrations.DeleteModel(
            name='ElectronicEquipment',
        ),
        migrations.DeleteModel(
            name='ReceiverandRemote',
        ),
        migrations.DeleteModel(
            name='touchKeys',
        ),
    ]
