# Generated by Django 5.0.1 on 2024-02-22 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('product', models.TextField(blank=True, max_length=1000)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('paymentmethod', models.CharField(blank=True, max_length=200)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(auto_now=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredat', models.DateTimeField(auto_now=True)),
                ('createdat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shippingaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('nocode', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('capital', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='zibal',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('transId', models.CharField(max_length=100, unique=True)),
                ('lastStatus', models.IntegerField(blank=True, null=True)),
                ('amountPaid', models.IntegerField(blank=True, null=True)),
                ('datepaid', models.DateTimeField(auto_now_add=True)),
                ('cardNo', models.CharField(blank=True, max_length=30, null=True)),
                ('Condition', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
