# Generated by Django 5.0.1 on 2024-01-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NavbarItems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dasteha',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='zirdaste',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dastehaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daste', to='NavbarItems.dasteha')),
            ],
        ),
        migrations.DeleteModel(
            name='electronicalParts',
        ),
        migrations.DeleteModel(
            name='ElectronicEquipment',
        ),
        migrations.DeleteModel(
            name='ReceiverandRemote',
        ),
        migrations.DeleteModel(
            name='touchKeys',
        ),
    ]
