# Generated by Django 5.0.1 on 2024-01-29 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NavbarItems', '0002_dasteha_zirdaste_delete_electronicalparts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zirdaste',
            name='dastehaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zirdasteha', to='NavbarItems.dasteha'),
        ),
    ]
